nameOverride: ""
fullnameOverride: ""
kube-state-metrics:
  enabled: true
rbac:
  create: true
  additionalRulesForClusterRole: []
serviceAccount:
  create: true
  name: zabbix-service-account
zabbixProxy:
  enabled: true
  containerSecurityContext: {}
  resources: {}
  image:
    repository: zabbix/zabbix-proxy-sqlite3
    tag: alpine-trunk
    pullPolicy: IfNotPresent
    pullSecrets: []
  env:
    - name: ZBX_PROXYMODE
      value: 0
    - name: ZBX_HOSTNAME
      value: zabbix-proxy
    - name: ZBX_SERVER_HOST
      value: "127.0.0.1"
    - name: ZBX_DEBUGLEVEL
      value: 3
    - name: ZBX_CACHESIZE
      value: 128M
    - name: ZBX_JAVAGATEWAY_ENABLE
      value: false
    - name: ZBX_PROXYCONFIGFREQUENCY
      value: 10
  service:
    annotations: {}
    labels: {}
    type: ClusterIP
    port: 10051
    targetPort: 10051
    externalIPs: []
    loadBalancerIP: ""
    loadBalancerSourceRanges: []
  nodeSelector: {}
  tolerations: {}
  affinity: {}
  persistentVolume:
    enabled: false
    accessModes:
      - ReadWriteOnce
    annotations: {}
    existingClaim: ""
    mountPath: /data
    size: 2Gi
    storageClass: "-"
    volumeBindingMode: ""
    subPath: ""
zabbixAgent:
  enabled: true
  resources: {}
  securityContext: {}
  containerSecurityContext: {}
  hostNetwork: true
  dnsConfig: {}
  hostPID: true
  hostRootFsMount: true
  extraHostVolumeMounts: []
  image:
    repository: zabbix/zabbix-agent2
    tag: alpine-trunk
    pullPolicy: IfNotPresent
    pullSecrets: []
  env:
    - name: ZBX_SERVER_HOST
      value: 0.0.0.0/0
    - name: ZBX_SERVER_PORT
      value: 10051
    - name: ZBX_PASSIVE_ALLOW
      value: true
    - name: ZBX_ACTIVE_ALLOW
      value: false
    - name: ZBX_DEBUGLEVEL
      value: 3
    - name: ZBX_TIMEOUT
      value: 4
  nodeSelector:
    kubernetes.io/os: linux
  tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/control-plane
  affinity: {}
  serviceAccount:
    create: true
    name: zabbix-agent-service-account
    annotations: {}
    imagePullSecrets: []
    automountServiceAccountToken: false
  service:
    type: ClusterIP
    port: 10050
    targetPort: 10050
    nodePort: 10050
    portName: zabbix-agent
    listenOnAllInterfaces: true
    annotations:
      agent.zabbix/monitor: "true"
  rbac:
    create: true
    pspEnabled: false
    pspAnnotations: {}

